# bark colorscheme for kovidgoyal/kitty by https://github.com/if-not-nil
background #101010
foreground #d0d0d0
selection_background #2b2b2b
selection_foreground #101010
url_color #b0b0b0
cursor #d0d0d0
active_border_color #505050
inactive_border_color #202020
active_tab_background #101010
active_tab_foreground #d0d0d0
inactive_tab_background #202020
inactive_tab_foreground #b0b0b0
tab_bar_background #202020

# normal
color0 #101010
color1 #ab4642
color2 #a1b56c
color3 #f7ca88
color4 #7cafc2
color5 #ba8baf
color6 #86c1b9
color7 #d0d0d0

# bright
color8 #505050
color9 #ab4642
color10 #a1b56c
color11 #f7ca88
color12 #7cafc2
color13 #ba8baf
color14 #86c1b9
color15 #e0e0e0
