# vim:fileencoding=utf-8:foldmethod=marker
shell zsh
include ./bark.conf
macos_option_as_alt left
clear_all_shortcuts yes

map cmd+v paste_from_clipboard
map cmd+, load_config_file

# font

#
# if the window has that annoying little gap up top
# uncomment maple mono nl nf 16, apply, then set whatever font you need
#

font_family Maple Mono NL NF
font_size 16.0

# font_family Terminess Nerd Font Mono
# font_size 22.0

#:  increase
map cmd+equal       change_font_size all +2.0
map cmd+plus        change_font_size all +2.0
map shift+cmd+equal change_font_size all +2.0
#:  decrease
map cmd+minus       change_font_size all -2.0
map shift+cmd+minus change_font_size all -2.0
#:  reset
map cmd+0           change_font_size all 0

# fullscreen
map cmd+shift+f toggle_fullscreen
map cmd+q close

hide_window_decorations                  yes
macos_traditional_fullscreen             yes
macos_fullscreen_ignore_safe_area_insets no
